name: Publish Development Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build
        run: ./gradlew build -Pgithub_sha=${{ github.sha }}

      - name: VirusTotal
        id: virustotal_step
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          request_rate: 4
          files: |
            ./build/libs/*.jar

      - name: Pretty Result
        id: pretty_result
        run: |
          echo "virus_total_link=$(echo ${{ steps.virustotal_step.outputs.analysis }} | cut -d ',' -f 1 | cut -d '=' -f 2-)" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "file=$(ls build/libs/*.jar | head -n 1)" >> $GITHUB_OUTPUT
          echo "file_name=$(ls build/libs/*.jar | head -n 1 | xargs -n 1 basename)" >> $GITHUB_OUTPUT
          echo "version=$(ls build/libs/*.jar | head -n 1 | xargs -n 1 basename | cut -d '-' -f 2 | cut -d '.' -f 1-3)" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Dev Build (Based on ${{ steps.pretty_result.outputs.version }})}}
          tag_name: latest
          prerelease: true
          draft: false
          body: "${{ steps.github_release.outputs.changelog }}\n VirusTotal analysis: ${{ steps.pretty_result.outputs.virus_total_link }}"
          files: |
            ${{ steps.pretty_result.outputs.file }}
